# Testing configuration
services:
  # server service container configuration
  server:
    environment:
      - NODE_ENV=test
    command: "npm run test:watch"

  # mongodb primary node service container configuration
  mongodb-primary:
    volumes:
      - mongo-test-prime:/data/db

  # mongodb secondary1 node service container configuration
  mongodb-secondary1:
    volumes:
      - mongo-test-sec1:/data/db

  # mongodb secondary2 node service container configuration
  mongodb-secondary2:
    volumes:
      - mongo-test-sec2:/data/db

# volumes configuration
volumes:
  mongo-test-prime:
    name: mongo-test-prime
  mongo-test-sec1:
    name: mongo-test-sec1
  mongo-test-sec2:
    name: mongo-test-sec2
