# Development configuration
services:
  # server service container configuration
  server:
    environment:
      - NODE_ENV=dev
    command: "npm run start:dev"

  # mongodb primary node service container configuration
  mongodb-primary:
    volumes:
      - mongo-dev-prime:/data/db

  # mongodb secondary1 node service container configuration
  mongodb-secondary1:
    volumes:
      - mongo-dev-sec1:/data/db

  # mongodb secondary2 node service container configuration
  mongodb-secondary2:
    volumes:
      - mongo-dev-sec2:/data/db

# volumes configuration
volumes:
  mongo-dev-prime:
    name: mongo-dev-prime
  mongo-dev-sec1:
    name: mongo-dev-sec1
  mongo-dev-sec2:
    name: mongo-dev-sec2
